---
dependency:
  name: galaxy
  options:
    requirements-file: ../requirements.yml

driver:
  name: docker

platforms:
  - name: fedora36
    image: docker.io/geerlingguy/docker-fedora36-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

  - name: fedora37
    image: docker.io/geerlingguy/docker-fedora37-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

  - name: fedora38
    image: docker.io/geerlingguy/docker-fedora38-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_CONVERGE_PLAYBOOK:-converge.yml}
    verify: ${MOLECULE_VERIFY_PLAYBOOK:-verify.yml}

scenario:
  name: fedora
  test_sequence:
    - destroy
    - create
    - converge
    - idempotence
    - verify
    - destroy
