---
- name: Import tasks to verify configuration
  ansible.builtin.import_tasks:
    file: 00-verify.yml

- name: Gather system information regarding target platform
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution
      - distribution_major_version
    gather_timeout: "{{ var_system_update_gather_timeout }}"

- name: End host if not one of supported platforms
  when: >
    (ansible_facts['distribution'] not 'RedHat' and
    ansible_facts['distribution_major_version'] not in [8, 9]) or
    (ansible_facts['distribution'] not 'Fedora' and
    ansible_facts['distribution_major_version'] not in [36, 37, 38])
  ansible.builtin.meta: end_host

- name: Import tasks to perform updates
  ansible.builtin.import_tasks:
    file: 10-updates.yml

- name: Reboot if system packages were updated
  become: true
  when:
    - not var_system_update_prevent_reboot
    - reg_system_update_packages['changed'] | default(false) or
      reg_system_update_security['changed'] | default(false) or
      reg_system_update_bugfix['changed'] | default(false)
  ansible.builtin.reboot:
    pre_reboot_delay: "{{ var_system_update_pre_reboot_delay }}"
    reboot_timeout: "{{ var_system_update_reboot_delay }}"
