---
- name: Import tasks to verify configuration
  ansible.builtin.import_tasks:
    file: 00-verify.yml

- name: Gather system information regarding target platform
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution
      - distribution_major_version
    gather_timeout: "{{ var_system_update_gather_timeout }}"

- name: Import tasks to perform updates on RHEL systems
  when:
    - ansible_facts['distribution'] == 'RedHat'
    - ansible_facts['distribution_major_version'] in [8, 9])
  ansible.builtin.import_tasks:
    file: 10-updates.yml

- name: Import tasks to perform updates on Fedora systems
  when:
    - ansible_facts['distribution'] == 'Fedora'
    - ansible_facts['distribution_major_version'] in [36, 37, 38])
  ansible.builtin.import_tasks:
    file: 10-updates.yml

- name: Ensure pending handlers are flushed
  ansible.builtin.meta: flush_handlers
